### ISSUE TITLE
Search width

### ISSUE THREAD

**Issue by Yelles** [Abhi0725/nova-create-or-add#4]
Hi,

Thanks for this great package.

Any idea why the size is not the same as the other search box ?

<img width="483" alt="cleanshot 2019-02-12 at 17 07 16 2x" src="https://user-images.githubusercontent.com/689478/52649461-a9f1d780-2ee8-11e9-92c2-aba06b7a3b78.png">

**Comment by shivanshrajpoot** [comment]
Yes because we are using select for dropdown and in nova it has fixed size

**Comment by Yelles** [comment]
Ok, thanks for the info !
