### ISSUE TITLE
Create Button Localization

### ISSUE THREAD

**Issue by Yelles** [Abhi0725/nova-create-or-add#5]
Hi, how to localize (in other language) the **Create New XXX** button ?

**Comment by shivanshrajpoot** [comment]
It uses resource name for displaying button.

**Comment by Yelles** [comment]
Yes i see, but since all my admin is in french, its the only button in english (create new), i was wondering if there a solution for that

**Comment by shivanshrajpoot** [comment]
You could fork the package and pass the localised string for button creation.

**Comment by Yelles** [comment]
Ok, thanks for your quick answer ;)
