### ISSUE TITLE
Empty form when i click on « create new XXX » 

### ISSUE THREAD

**Issue by Ange7** [Abhi0725/nova-create-or-add#6]
I have one empty form when a click on « Create new xxx » without JS error fields seems loaded correctly

![peek 15-02-2019 16-22](https://user-images.githubusercontent.com/4114703/52865977-0568d300-313e-11e9-972d-ffa1da7b7d4a.gif)

**Comment by sabid** [comment]
The same error

**Comment by Ange7** [comment]
Nobody have idea to solve this problem ?

**Comment by Ange7** [comment]
It seems i have this error with Chrome : 

`
tveyne [9 h 47]
TypeError: Cannot read property ‘status’ of undefined
   at p._callee3$ (nova-create-or-add:44049)
   at tryCatch (nova-create-or-add:43121)
   at Generator.invoke [as _invoke] (nova-create-or-add:43355)
   at Generator.prototype.(anonymous function) [as next] (https://mydomain.com/nova-api/scripts/nova-create-or-add:43173:21)
   at step (nova-create-or-add:43848)
   at nova-create-or-add:43848
   at new Promise (<anonymous>)
   at p.<anonymous> (nova-create-or-add:43848)
   at p.createResource (nova-create-or-add:44062)
   at submit (nova-create-or-add:44160)
`

Or with Safari : 

`TypeError: undefined is not an object (evaluating ‘_context3.t0.response.status’)
_callee3$ — nova-create-or-add:44049
tryCatch — nova-create-or-add:43121
invoke — nova-create-or-add:43355
step — nova-create-or-add:43848:192
initializePromise
Promise
(fonction anonyme) — nova-create-or-add:43848:111
createResource
submit — nova-create-or-add:44160
Yt — vendor.js:32888
jt — vendor.js:32908
Pt — vendor.js:32903
Ft — vendor.js:32883
promiseReactionJob`

**Comment by Ange7** [comment]
Nobody have idea ?

**Comment by shivanshrajpoot** [comment]
@Ange7 I think you have not created the resource required for rendering the form.

**Comment by Ange7** [comment]
@shivanshrajpoot i'm not sure to understand what reason can do that « i don't have created the resource required for rendering the form »

**Comment by shivanshrajpoot** [comment]
@Ange7 I think the the resource you are trying to create using this package does not exists in the Resources directory, e.g. User->BelongsTo->Company, So you have not created Company Resource in the nova Resources directory.

**Comment by Ange7** [comment]
1. in « project » resource, i have : `NovaCreateOrAdd::make('Customer')->searchable()->rules('required'),`

2. In « project » model, i have :
```
public function client()
    {
        return $this->belongsTo(Customer::class, 'idCustomer', 'id');
    }
```

That's all...

**Comment by shivanshrajpoot** [comment]
You have to make the parent Resource for the relation so that the package can fetch form fields in from the Resource file, e.g. if Customer belongsTo SomeModel then you will also have to create a resource file for mofel SomeModel.

**Comment by Ange7** [comment]
it's already case, i have project resource, customer resource, project model and customer model.

**Comment by shivanshrajpoot** [comment]
So do you have customer resource fields function returning a number of fields?

**Comment by Ange7** [comment]
@shivanshrajpoot Yes. 

and it's the response of ajax request when i click on « create new customer »  : 

![image](https://user-images.githubusercontent.com/4114703/53643896-9313ea80-3c35-11e9-8314-de7828cdb77a.png)

So the query is OK and answer seems to be ok.

**Comment by shivanshrajpoot** [comment]
Can you please share your models and resources file ??

**Comment by Ange7** [comment]
it's shortcut of my resources and model 

[app.zip](https://github.com/Abhi0725/nova-create-or-add/files/2919967/app.zip)

**Comment by shivanshrajpoot** [comment]
Sure I will get back to you soon! I'm off to bed! 💤💤

**Comment by Ange7** [comment]
someone have same problem ?

**Comment by shivanshrajpoot** [comment]
> someone have same problem ?

I have looked into your files, I did not find any problem with those, I think that might be an issue with nova version, please check into the resources files and try to debug that also I have merged a latest build, please try with that. Sorry I was busy a little, so couldn't reply earlier.
